### ISSUE TITLE
Import of duplicate BSA IDs isn't properly handled

### ISSUE THREAD

**Issue by vaindil** [oabsa/dues-lookup#20]
Since LodgeMaster doesn't currently check for duplicate BSA IDs the plugin probably should. The current release imports the first value from the spreadsheet then throws an error about (and ignores) the second one.

The plugin should catch the error and print a message after the import that the BSA ID (and associated member information) was ignored--just drop that member from the database because the problem will need to be manually fixed and no information is better than erroneous information in my opinion.

Another option would be to scan the spreadsheet's BSA ID values before importing any, and print an error for/don't attempt to import any duplicates. This is probably the better option but could potentially cause minor performance issues when importing larger spreadsheets. Will take a better look later today.

**Comment by justdave** [comment]
99% of the time if the BSA Audits have been run, the one that's correct will show Registered or Not Registered and the one that's not will show No Match Found for the audit result.  Since the audit results are included in the data set we get on import, it would make sense to pay attention to that.

**Comment by justdave** [comment]
@vaindil still planning to tackle this? (it's been 4 years). If not, can you unassign yourself?

As of a couple months ago, OALM actually prevents you from adding duplicate BSA IDs. But I'm not sure they did anything about existing duplicates already in the database.

**Comment by vaindil** [comment]
Oh wow, it has been a while. I'll unassign myself, sorry.

**Comment by justdave** [comment]
FWIW, LodgeMaster actually does check for duplicate BSA IDs now.  Only on new imports though, there's still a possibility of legacy data with duplicates.

**Comment by justdave** [comment]
Going to close this out since OALM forces them unique now.
