### ISSUE TITLE
Successful Import goes to "Page Not Found"

### ISSUE THREAD

**Issue by MatthewA1** [oabsa/dues-lookup#23]
After completing an import, instead of going back to the settings page, it takes me to the WordPress themes "Page Not Found" page.
The URL is the same as the settings page (/wp-admin/options-general.php?page=oadueslookup), so it seems it has something to do in the handling of the POST request.

**Comment by justdave** [comment]
This usually means the processing took longer than your PHP max_execution_time setting is set for (and it may or may not have actually completed before the process got killed).  You would need to set your max_execution_time setting longer and try again.  How to set this depends on your hosting provider, usually it's in a php.ini or phprc file somewhere.

**Comment by MatthewA1** [comment]
It must have been the execution time, as uploading the same file worked a few times, but when I checked the database, it usually was incomplete.

**Comment by justdave** [comment]
I've added this workaround to the Download and Installation section in the docs.
