### ISSUE TITLE
Update for LodgeMaster 4.2.0 Compatibility

### ISSUE THREAD

**Issue by justdave** [oabsa/dues-lookup#25]
LodgeMaster 4.2.0 made fundamental changes to the way BSA Membership validation is handled, in a way that breaks this plugin.  The plugin will need updating to handle the new BSA membership-related fields.

**Comment by ericjsilva** [comment]
@justdave can you be more specific with the break? I may have some time to work on this in the next couple of weeks.

**Comment by justdave** [comment]
The audit results are now split into two different fields, one with whether the BSA ID matched or not, and the other with whether your membership is valid. The membership valid one should be ignored if the BSA ID one says it mismatched. The terms used to describe the states have changed as well. Membership valid is going to be a Yes or No, verification status is going to have a few different string terms that I don't remember off the top of my head.  The instructions on the wiki for how to make the export will need to be changed as well since the old columns are gone.

**Comment by ericjsilva** [comment]
@justdave I am working on this today.

**Comment by justdave** [comment]
Awesome, thanks! I was actually going to take a crack at it myself this afternoon, finally, but I have a few meetings at church yet so it'll be 4 or 5 hours before I would have gotten to it l.

**Comment by ericjsilva** [comment]
@justdave I submitted PR #26 for you to review. I've tested this out on my lodge's website if you want to view it working.

https://kittatinny5.org/dueslookup/

You can use the following IDs to test: 118253457 (valid; verified); 128410046 (data mismatch); 125064152 (never run; new); 1285077911 (not found)

128410046
--

**Comment by justdave** [comment]
Resolved by PR #26
