### ISSUE TITLE
Offer to print membership cards if the member is registered and current

### ISSUE THREAD

**Issue by justdave** [oabsa/dues-lookup#27]
This is in the food for thought stage at this point, though I have sort of a prototype on my lodge website currently.  It needs some thought put into it before we can actually deploy it.

I have successfully created a downloadable membership card dynamically using the dompdf library which can be pulled in via composer.  An example card is attached:
[OAMembershipCard-15.pdf](https://github.com/oabsa/dues-lookup/files/2873507/OAMembershipCard-15.pdf)

Some things that need to be considered:

1) since you need the person's name (and optionally their chapter and unit) in order to print the card, you would need to include more data in the dump from LodgeMaster to upload to the website.
2) With the current process, you could potentially enumerate names of members by throwing in random ID numbers and downloading cards. We would probably need to change the lookup to request both their last name and the ID number instead of just the ID number, so that you would need to already know who it belonged to in order to look it up.
3) I suspect it wouldn't be legal for us to distribute the blank card images with the plugin, since they contain BSA trademarked logos, etc., and I doubt national wants high quality blank images floating around on the net. We might need to include instructions for what dimensions and DPI to make the images and let people scan their own if they want to use the feature.

**Comment by ericjsilva** [comment]
@justdave I thought this was going to be a feature of OALM in an upcoming release. OA members would be able to print their own ID card via Lodgemaster.

**Comment by justdave** [comment]
This entire plugin is supposed to be a feature of OALM in an upcoming release.  So yeah, it's got a limited lifespan.  I'm guessing the member portal in OALM is about a year away still though.

**Comment by justdave** [comment]
> This entire plugin is supposed to be a feature of OALM in an upcoming release. So yeah, it's got a limited lifespan. I'm guessing the member portal in OALM is about a year away still though.

Famous last words. 😜  We're a couple months short of being 2 years since I posted that, and it looks like we're going to be about 6 months yet before that part of the portal is in place it sounds like.

I need to have this implemented for my lodge ASAP regardless because we're merging, and my staff advisor skimped on blank cards the last couple years so I haven't been able to print any real ones.  Need to give people an opportunity to print their cards with the old lodge name before it goes away.

**Comment by justdave** [comment]
This is now implemented in LodgeMaster's member portal.
