### ISSUE TITLE
PHP Syntax Error when Import new .XLSX file 

### ISSUE THREAD

**Issue by huryotch** [oabsa/dues-lookup#30]
I recently tried to import a new exel sheet with the correct specification but instead I get this error 

"Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /home2/mikiweb/sites/miki2015/wp-content/plugins/oadueslookup/vendor/markbaker/matrix/classes/src/operations/add.php on line 21"

**Comment by ericjsilva** [comment]
@huryotch there should be no personal information contained in the file. Are you comfortable sharing the file with us to analyze? You can send it to me at ericjsilva@gmail.com.

**Comment by ericjsilva** [comment]
@huryotch Can you tell me what version of Wordpress and PHP you are using? This error is typically caused by PHP versions less than 5.6.

**Comment by huryotch** [comment]
I had a sneaking suspision that might be the problem, I just wasnt sure. 
I am using Wordpress 5.1 and PHP 5.4.45

**Comment by ericjsilva** [comment]
@huryotch The plugin is supported in PHP versions 5.6+. PHP 5.4 went end of life in Sept 2015. 5.6 went end of life at the end of 2018. We advise upgrading to PHP 7.2 if at all possible.
