### ISSUE TITLE
Receiving the following PHP Error

### ISSUE THREAD

**Issue by troyrutter** [oabsa/dues-lookup#31]
Hello, I am receiving the following error:

PHP Version 5.4.45

/wp-content/plugins/dues-lookup-master/includes/../vendor/autoload.php' (include_path='.:/opt/php54/lib/php') in /home2/mitigwa/public_html/wp-content/plugins/dues-lookup-master/includes/management-options-page.php on line 46

Any ideas? Thanks!

**Comment by troyrutter** [comment]
Thinking it might be the PHP version as well.

**Comment by ericjsilva** [comment]
@troyrutter You need to be running PHP 5.6+. Ideally you should upgrade to PHP 7.2.

**Comment by troyrutter** [comment]
Thanks, working on that now. Have had this server since 2013 . :D
