### ISSUE TITLE
PHP 7.2 / PHP 7.3 error when importing .xlsx from OALM

### ISSUE THREAD

**Issue by mikegray15** [oabsa/dues-lookup#32]
I am receiving the following error when trying to upload the .xlsx sheet from OALM:

> Warning: require_once(/homepages/13/d760092943/htdocs/app760092952/wp-content/plugins/dues-lookup-master/includes/../vendor/autoload.php): failed to open stream: No such file or directory in /homepages/13/d760092943/htdocs/app760092952/wp-content/plugins/dues-lookup-master/includes/management-options-page.php on line 46

> Fatal error: require_once(): Failed opening required '/homepages/13/d760092943/htdocs/app760092952/wp-content/plugins/dues-lookup-master/includes/../vendor/autoload.php' (include_path='.:/usr/lib/php7.2') in /homepages/13/d760092943/htdocs/app760092952/wp-content/plugins/dues-lookup-master/includes/management-options-page.php on line 46

I'm running `WordPress 5.2.3` and was using `PHP 7.2` while getting the error. I switched to `PHP 7.3` to see if that would help, but error message is the same.

**Comment by ericjsilva** [comment]
@mikegray15 when downloading directly from the repo, you have to run a few commands to download the dependencies from composer.  When we make a release we bundle the dependencies in the zip file. I will make a note to update the documentation to make that much more clear.
